"""Razorpay webhook signature verification using exact raw request body bytes."""

import hashlib
import hmac
import logging
from typing import Union

logger = logging.getLogger("recovery_autopilot.integrations.razorpay.webhook_verifier")


class WebhookVerificationError(ValueError):
    """Raised when webhook signature verification fails."""
    pass


class RazorpayWebhookVerifier:
    """Verifies HMAC SHA256 signatures generated by Razorpay webhooks.

    Safety:
    Razorpay signatures must be computed on the exact raw body bytes before JSON decoding.
    """

    def __init__(self, webhook_secret: str):
        self.webhook_secret = webhook_secret

    def compute_signature(self, raw_body: Union[bytes, str]) -> str:
        """Calculate HMAC SHA256 hex digest for body bytes."""
        if isinstance(raw_body, str):
            body_bytes = raw_body.encode("utf-8")
        else:
            body_bytes = raw_body

        return hmac.new(
            self.webhook_secret.encode("utf-8"),
            body_bytes,
            hashlib.sha256,
        ).hexdigest()

    def verify(self, raw_body: Union[bytes, str], signature: str) -> bool:
        """Verify that signature matches raw body. Returns True if valid, raises WebhookVerificationError if invalid."""
        if not signature:
            raise WebhookVerificationError("Missing X-Razorpay-Signature header")

        expected_sig = self.compute_signature(raw_body)

        # Constant-time comparison to prevent timing attacks
        if not hmac.compare_digest(expected_sig, signature):
            logger.warning("Razorpay webhook signature mismatch detected")
            raise WebhookVerificationError("Invalid webhook signature")

        return True
